version: '3.8'

services:

  db:
    image: postgres:17-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=marquin
      - POSTGRES_PASSWORD=post1929
      - POSTGRES_DB=gold_seller
    ports:
      - "5499:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - minha-rede
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U marquin -d gold_seller" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  app:
    container_name: image-goldseller

    build: .
    ports:
      - "8080:8080"  # Mapeia a porta da aplicação Spring.
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Configurações para a aplicação Spring se conectar ao banco 'db'.
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gold_seller
      - SPRING_DATASOURCE_USERNAME=marquin
      - SPRING_DATASOURCE_PASSWORD=post1929
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - minha-rede # Conecta este serviço à mesma rede do banco.

# Definição dos volumes
volumes:
  postgres-data:

# Definição das redes
networks:
  minha-rede:
    driver: bridge