version: '3.8'

services:

  db:
    image: postgres:14.1-alpine  # Usamos uma imagem oficial do PostgreSQL.
    container_name: postgres-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=gold_seller_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - minha-rede # Conecta este serviço a uma rede customizada.
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d gold_seller_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  app:
    container_name: image-goldseller

    build: .
    ports:
      - "8080:8080"  # Mapeia a porta da aplicação Spring.
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Configurações para a aplicação Spring se conectar ao banco 'db'.
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gold_seller_db
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - minha-rede # Conecta este serviço à mesma rede do banco.

# Definição dos volumes
volumes:
  postgres-data:

# Definição das redes
networks:
  minha-rede:
    driver: bridge